### ISSUE TITLE
improvement to use https-keyscript

### ISSUE THREAD

**Issue by superuser5** [unixabg/cryptmypi#16]
Hello,
I would like to propose improvement and can test it and will try implement it myself, just not sure how correctly integrate it with your hooks:

The below project designed to fetch key with url or enter manually if url is not accessible:
Allow a machine with an encrypted boot drive to passwordlessly boot by fetching a key over HTTPS.

https://github.com/stupidpupil/https-keyscript

the releases section has latest binary: 
https://github.com/stupidpupil/https-keyscript/releases/download/v1.0.3/https-keyscript_1.0.3_all.deb

thank you

**Comment by unixabg** [comment]
Greetings,
I have thought about this for some time now and I am at this point not going to include in project. If I wanted to have this included in my build, I believe I would script it with the stage2-otherscript.sh. Also in said script I would call  the chroot_mkinitramfs function instead of update-initramfs -u that the instructions at the site suggests. For users who might want this feature if you get it working in stage2-otherscript.sh I would be glad to take example in PR or some form and place the example in other folder. Thank you for your submission of idea.
